title: deXfrost
email: rdthlx@outlook.com
description: > #Make a quote
  This blog created for sharing my experience (ofc not everything).
  I like sharing something and if you curious about me just contact 
  by email. Happy reading!
  
permalink: ':title/:year/:month/:day/:title'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Akwila  Feliciano # add your name
author-pic: felix-pic
about-author: Hi there, my name is Akwila Feliciano P. You can call me Felix. I'm student at Informatics ITS.  
              I have passion in technology development. I'm still learning about web and others.
              
# Contact links
email: rdthlx@outlook.com # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: pradiptlx # Add your Github handle
twitter: '@Akwilaafp_' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: 'pradiptlx' # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
#discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
